// <auto-generated />
using AnimeRepo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeRepo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240313150615_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeRepo.Models.AnimeModel", b =>
                {
                    b.Property<int>("AnimeModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimeModelId"));

                    b.HasKey("AnimeModelId");

                    b.ToTable("AnimeModels");
                });

            modelBuilder.Entity("AnimeRepo.Models.GenreModel", b =>
                {
                    b.Property<int>("GenreModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreModelId"));

                    b.Property<int?>("AnimeModelId")
                        .HasColumnType("int");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreModelId");

                    b.HasIndex("AnimeModelId");

                    b.ToTable("GenreModels");
                });

            modelBuilder.Entity("AnimeRepo.Models.GenreModel", b =>
                {
                    b.HasOne("AnimeRepo.Models.AnimeModel", null)
                        .WithMany("Genre")
                        .HasForeignKey("AnimeModelId");
                });

            modelBuilder.Entity("AnimeRepo.Models.AnimeModel", b =>
                {
                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
