// <auto-generated />
using AnimeRepo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeRepo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeModelGenreModel", b =>
                {
                    b.Property<int>("AnimeModelsAnimeModelId")
                        .HasColumnType("int");

                    b.Property<int>("GenreModelId")
                        .HasColumnType("int");

                    b.HasKey("AnimeModelsAnimeModelId", "GenreModelId");

                    b.HasIndex("GenreModelId");

                    b.ToTable("AnimeModelGenreModel");
                });

            modelBuilder.Entity("AnimeRepo.Models.AnimeModel", b =>
                {
                    b.Property<int>("AnimeModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimeModelId"));

                    b.Property<string>("AnimeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimeModelId");

                    b.ToTable("AnimeModels");
                });

            modelBuilder.Entity("AnimeRepo.Models.GenreModel", b =>
                {
                    b.Property<int>("GenreModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreModelId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreModelId");

                    b.ToTable("GenreModels");
                });

            modelBuilder.Entity("AnimeModelGenreModel", b =>
                {
                    b.HasOne("AnimeRepo.Models.AnimeModel", null)
                        .WithMany()
                        .HasForeignKey("AnimeModelsAnimeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeRepo.Models.GenreModel", null)
                        .WithMany()
                        .HasForeignKey("GenreModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
